### ISSUE TITLE
When do you create the 2021-fall application pages?

### ISSUE THREAD

**Issue by yuchenlichuck** [SUSTech-Application/2021-Fall#31]
Hi, there,

This is a senior from SUSTech. Because of the pandemic, this year students chose more to become a graduate in China. Some has already got the offer, could you please kindly create 2021-fall application pages?

Thanks a lot,
Best Regards,

**Comment by ERICXUCHI** [comment]
Thanks for your suggestion, sorry for the delay (just update my own files :-(). Now the name is changed, you can update any files if you want as well as look through others. Thank you again!
